### PR TITLE
Minor change in reqparse

### PR DESCRIPTION
**Pull request by Menda0**
I was having a problem generating parameters using reqparse parser. Sometimes I had a path parameters in my resources and I still want to use the request parser functionality. For that I used the *parameters* and *rerparser* properties in *@swagger.doc* like this:

```python
"reqparser": {
    "name": "User signup info",
    "parser": postreqparse
},
"parameters": [
    {
        "description": "User email",
        "in": "path",
        "name": "email",
        "type": "string",
        "required": True
    }
]
```

that provoke the following exception *'parameters and reqparser can\'t be in same spec'*.

```python
if 'parameters' in operation:
  raise ValidationError('parameters and reqparser can\'t be in same spec')
```

For that to work for me I wanted both the method to work together, like a concatenation of parameters and reqparser so the output should be like this

```python
"parameters": [
    {
        "description": "User email",
        "in": "path",
        "name": "email",
        "required": true,
        "type": "string"
    },
    {
        "description": "Request body",
        "in": "body",
        "name": "body",
        "required": true,
        "schema": {
            "$ref": "#/definitions/User signup info"
        }
    }
]
```

I fix this problem on this commit concatenating the result of *reqparse parser* and *parameters* and it worked as expected.
I think that could be useful for someone like that was for me. So thats the reason of this pull request.

Hope I helped,
Thanks for this awesome worked,

Cheers,
Marco Mendão

### CODE REVIEW

**Comment by niall-byrne** [comment]
I think given the scope of this change, and the state of the two projects, I'm going to close this PR.

**Comment by niall-byrne** [comment]
I'm actually not sure what to do with this one, I'm going to checkout the branch and play around with it.  @Menda0 @soerface what do you guys think, should we try to merge this in still?

Been a long time, but it would be a shame to lose all this work.

**Comment by niall-byrne** [comment]
Hi again guys, I'm very reluctant to close this PR, but I think it might be best to allow the two repositories to differentiate with the versions of the spec they support.  I'll wait a few days, incase you guys have thoughts on this.

**Comment by soerface** [comment]
Sorry, didn't realized my commits were in this pull request. My changes are definitely breaking, I realized that pretty much things were different between swagger 1 and 2. So IF we want to merge, it would be more like a "if swagger 1 use this package otherwise use the other package".

Also, I'm currently have no time to support my package, so I also won't be able to contribute to this one, too. I guess co-existents of both packages seems like a good solution.

**Comment by niall-byrne** [comment]
Sounds good, I'll start redirecting folks looking for this functionality to your project.

**Pull request closed without merging**
