### PR TITLE
add reqparser option to use restful's RequestParser

### PR DESCRIPTION
**Pull request by dases**
Per #18. I've been using this for months now and it's working well for me.
Example usage code in the updated README. The example code in my early comment on the issue is still valid too.

### CODE REVIEW

**Comment by JamieCressey** [comment]
+1

**Comment by griffinqiu** [comment]
+10086

**Comment by na-ji** [comment]
+9665494645416414

**Comment by niall-byrne** [comment]
@dases Do you have any interest in rebasing your changes here so we could take a look at them and potentially close this out?

**Comment by dases** [comment]
@niall-byrne With respect, no longer have any interest in it. The pull request dates back more than 5 years and I've long since transitioned to using flask-apispec in my projects instead.
Please feel free to take what you want from the changes provided.
Best wishes!

**Pull request closed without merging**
