### PR TITLE
Create custom auth headers in swagger-ui

### PR DESCRIPTION
**Pull request by lucasnad27**
Please see the question I raised here: https://github.com/rantav/flask-restful-swagger/issues/100

This PR allows users to pass an optional kwarg that enables Authorization headers to be passed when given an API key

### CODE REVIEW

**Comment by sobolevn** [comment]
Hi! Thanks for your work.

Sorry for being so slow with the response. 
Right now we are slowly moving forwards new version: https://github.com/flask-restful-swagger/flask-restful-swagger

This is still an opened issue for the new version as well. Maybe you will be interested in participating in the development?

Cheers!

**Comment by lucasnad27** [comment]
I'd love to implement the auth headers in the new version. I'll take a look at the branch this weekend and see if I can help

**Comment by sobolevn** [comment]
@lucasnad27 you can contact @andyzt, since he's on top of the project's stuff.

**Comment by andyzt** [comment]
Hi! Yes, you can write me if you have any questions. Please pay attention that currently we are developing in version-1.0.0 branch: https://github.com/flask-restful-swagger/flask-restful-swagger/tree/version-1.0.0  It contains a lot of changes (the biggest is that it is object-oriented now)

**Pull request closed without merging**
